dist: trusty
language: c++
branches:
  only:
  - master
  - feature
before_install:
- sudo apt-get update
- sudo apt-get install -fy libsdl2-dev zlib1g-dev
- gem install fpm --version 1.11.0
script: make package
